name: 42 Norminette

on: [push]

jobs:
  norminette:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: 42 Norminette Linter
      uses: hanshazairi/42-norminette-action@v1.1.0
